name: Node.js CI

env:
  HOST: localhost
  USER: test_user
  PASSWORD: password
  DATABASE: test_db
  PORT: 3000
  BASE_URL: http://localhost:3000
  NODE_ENV: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  api-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
            PASSWORD: ${{ env.Password}}
            ROOT_PASSWORD: ${{ env.PASSWORD }}
            DATABASE: ${{ env.DATABASE }}
            USER: ${{ env.USER }}
            HOST: ${{ env.HOST }}
            BASE_URL: ${{ env.BASE_URL }}
        ports:
            - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: "npm"
      - run: npm ci
      - name: Run tests
        run: npm test
        env:
          PORT: ${{ env.PORT }}
      - run: npm run build
