name: Node.js CI

env:
  MYSQL_HOST: localhost
  MYSQL_USER: root
  MYSQL_PASSWORD: password
  MYSQL_DATABASE: database
  PORT: 3000
  NODE_ENV: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: "npm"
      - name: Setup MYSQL
        inputs:
          host port: ${{ env.PORT }}
          container port: ${{ env.PORT }}
          mysql version: 'latest'
          mysql root password: ${{ env.MYSQL_PASSWORD }}
          mysql database: ${{ env.MYSQL_DATABASE }}
          mysql user: ${{ env.MYSQL_USER }}
          mysql password: ${{ env.MYSQL_PASSWORD }}
        run: 'docker'

      - run: npm ci
      - run: npm test
      - run: npm run build
