name: Node.js CI

env:
  MYSQL_HOST: 127.0.0.1
  MYSQL_PASSWORD: password
  MYSQL_DATABASE: testdb
  PORT: 3306
  NODE_ENV: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
  - uses: mirromutth/mysql-action@v1.1
      with:
    mysql database: 'testdb'
    mysql root password: 'password'
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: "npm"
      - run: npm ci
      - name: MYSQL Setup
        run: mysql --host 127.0.0.1 --port 3306 -uroot -ppassword -e
               "GRANT ALL PRIVILEGES ON testdb.* TO 'root'@'127.0.0.1'"
      - name: Run tests
        run: npm test
        env:
          MYSQL_USER: root
          PORT: ${{ env.PORT }}
