name: Node.js CI

env:
  MYSQL_HOST: localhost
  MYSQL_USER: root
  MYSQL_PASSWORD: password
  MYSQL_DATABASE: database
  PORT: 3000
  NODE_ENV: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  api-tests:
    runs-on: ubuntu-latest

    env:
      MYSQL_HOST: ${{ env.MYSQL_HOST }}
      MYSQL_USER: ${{ env.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ env.MYSQL_PASSWORD }}
      MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_PASSWORD }}
      MYSQL_DATABASE: ${{ env.MYSQL_DATABASE }}
      PORT: ${{ env.PORT }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: "npm"
      - run: npm ci
      - run: npm test
      - run: npm run build
