name: Node.js CI
env:
  HOST: localhost
  USER: root
  PASSWORD: root
  DATABASE: test_db
  PORT: 3000
  BASE_URL: http://localhost:3000
  NODE_ENV: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

services:
    mysql:
        image: mysql:8.0
        env:
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
            MYSQL_DATABASE: test_db
        ports:
            - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: "npm"
      - run: npm ci
      - run: npm test
      - run: npm run build
