name: Node.js CI
env:
  HOST: localhost
  USER: root
  PASSWORD: root
  DATABASE: test_db
  PORT: 3000
  BASE_URL: http://localhost:3000
  NODE_ENV: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: "npm"
      - name: MYSQL setup
          run: sudo /etc/init.d/mysql start
              mysql -e 'CREATE DATABASE ${{ env.DATABASE }};' -u${{ env.USER }} -p${{ env.PASSWORD }}
      - run: npm ci
      - run: npm test
      - run: npm run build
