name: Node.js CI
env:
  MYSQL_HOST: localhost
  MYSQL_USER: root
  MYSQL_PASSWORD: password
  MYSQL_DATABASE: test_db
  PORT: 3000
  BASE_URL: http://localhost:3000
  NODE_ENV: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  api-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
            MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_PASSWORD }}
            MYSQL_DATABASE: ${{ env.MYSQL_DATABASE }}
            MYSQL_USER: ${{ env.MYSQL_USER }}
            MYSQL_HOST: ${{ env.MYSWL_HOST }}
        ports:
            - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: "npm"
      - run: npm ci
      - name: Run tests
        run: npm test
        env:
          PORT: ${{ env.PORT }}
      - run: npm run build
