name: Node.js CI
env:
  HOST: localhost
  USER: test_user
  PASSWORD: test_password
  DATABASE: test_database
  PORT: 3000
  NODE_ENV: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: "npm"
      - run: npm ci
      - run: npm test
      - run: npm run build
