name: Node.js CI

env:
  MYSQL_HOST: 127.0.0.1
  MYSQL_USER: test_user
  MYSQL_PASSWORD: password
  MYSQL_DATABASE: test_db
  PORT: 3306
  MYSQL_BASE_URL: 127.0.0.1:3306
  NODE_ENV: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  api-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
            MYSQL_PASSWORD: ${{ env.MYSQL_PASSWORD}}
            MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_PASSWORD }}
            MYSQL_DATABASE: ${{ env.MYSQL_DATABASE }}
            MYSQL_USER: ${{ env.MYSQL_USER }}
            MYSQL_HOST: ${{ env.MYSQL_HOST }}
            MYSQL_BASE_URL: ${{ env.MYSQL_BASE_URL }}
        ports:
            - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: "npm"
      - run: npm ci
      - name: Webpack bundler
        run: npm run build
      - name: MYSQL Setup
        run: sudo service mysql start
               mysql --host 127.0.0.1 --port 3306 -utest_user -ppassword -e
      - name: Run tests
        run: npm test
        env:
          PORT: ${{ env.PORT }}
